[{"type":"class","namespace":null,"meta":{"file":"\/Users\/clemens\/lib\/uml-generator-php\/vendor\/phpunit\/phpunit\/PHPUnit\/Framework\/TestFailure.php","output":"\/Users\/clemens\/lib\/uml-generator-php\/tests\/output\/vendor\/phpunit\/phpunit\/PHPUnit\/Framework\/TestFailure.json"},"name":"PHPUnit_Framework_TestFailure","children":[{"type":"attribute","name":"failedTest","visibility":"protected","scope":"instance"},{"type":"attribute","name":"thrownException","visibility":"protected","scope":"instance"},{"type":"method","name":"__construct","scope":"instance","parameters":[{"name":"failedTest","type":{}},{"name":"thrownException","type":{}}],"visibility":"public"},{"type":"method","name":"toString","scope":"instance","parameters":[],"visibility":"public"},{"type":"method","name":"getExceptionAsString","scope":"instance","parameters":[],"visibility":"public"},{"type":"method","name":"exceptionToString","scope":"classifier","parameters":[{"name":"e","type":{}}],"visibility":"public"},{"type":"method","name":"failedTest","scope":"instance","parameters":[],"visibility":"public"},{"type":"method","name":"thrownException","scope":"instance","parameters":[],"visibility":"public"},{"type":"method","name":"exceptionMessage","scope":"instance","parameters":[],"visibility":"public"},{"type":"method","name":"isFailure","scope":"instance","parameters":[],"visibility":"public"}],"traits":[],"implements":[]}]