[{"type":"class","namespace":"\\Symfony\\Component\\Finder\\Exception","meta":{"file":"\/Users\/clemens\/lib\/uml-generator-php\/vendor\/symfony\/finder\/Symfony\/Component\/Finder\/Exception\/AdapterFailureException.php","output":"\/Users\/clemens\/lib\/uml-generator-php\/tests\/output\/vendor\/symfony\/finder\/Symfony\/Component\/Finder\/Exception\/AdapterFailureException.json"},"name":"AdapterFailureException","children":[{"type":"attribute","name":"adapter","visibility":"private","scope":"instance"},{"type":"method","name":"__construct","scope":"instance","parameters":[{"name":"adapter","type":{}},{"name":"message","type":null},{"name":"previous","type":{}}],"visibility":"public"},{"type":"method","name":"getAdapter","scope":"instance","parameters":[],"visibility":"public"}],"traits":[],"extends":"\\RuntimeException","implements":["\\Symfony\\Component\\Finder\\Exception\\ExceptionInterface"]}]